### ISSUE TITLE
Review CSS

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/moose-wiki#7]
In the http://modularmoose.org/ site, page [https://moosetechnology.github.io/moose-wiki/Developers/predefinedEntities.html](https://moosetechnology.github.io/moose-wiki/Developers/predefinedEntities.html) the "View UML" links appear as normal text with absolutely no hint that they are clickable.

**Comment by fuhrmanator** [comment]
This may be related to the challenges fixed by https://github.com/moosetechnology/moose-wiki/commit/11cf87379361191c32bf3bd15612440c83ab75e7 - it is frustrating that GitHub pages markdown and GitHub.com's markdown are not the same.

**Comment by fuhrmanator** [comment]
In the "good" rendering, here's what I see in the CSS for GitHub.com's markdown rendering:

```css
details summary {
    cursor: pointer;
}
```

Maybe it's possible to add this with a `<style ...>` block on the markdown that creates that page? The best way to test is with Jekyll installed. I will give it a try on my local clone.

**Comment by badetitou** [comment]
Nice @fuhrmanator 
Thanks!
